---
pipeline:
  name: nj-campaign-finance-contributions-check
transform:
  image: publicintegrity/state-cf-loaders:00579f08f10b
  cmd:
  - bash
  stdin:
  - ./nj/transforms/check.sh /pfs/out
parallelism_spec:
  constant: 1
input:
  cron:
    name: tick
    spec: "@daily"
